---
swagger: "2.0"
info:
  description: "Bla bla bla"
  version: "1.0.0"
  title: "bla"
host: "localhost:8080"
basePath: "/"
tags:
- name: "runner"
  description: "Operations about user"
schemes:
- "http"
- "https"
paths:
  /runners:
    post:
      tags:
      - "runner"
      summary: "Create user"
      description: "Create a new user"
      operationId: "createRunner"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Runner"
      responses:
        201:
          description: "successful operation"
          headers:
            Location:
              type: "string"
      x-swagger-router-controller: "Runner"
  /runners/{username}:
    get:
      tags:
      - "runner"
      summary: "Get runner"
      description: "Get a runner"
      operationId: "getRunner"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The username of the runner"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Runner"
        404:
          description: "Team not found"
      x-swagger-router-controller: "Runner"
    put:
      tags:
      - "runner"
      summary: "Modify runner"
      description: "Modify runner"
      operationId: "updateRunner"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The username of runner"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Modified team object"
        required: true
        schema:
          type: "integer"
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "Runner"
  /org:
    post:
      tags:
      - "org"
      summary: "Create org"
      description: "Create a new team"
      operationId: "createOrg"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created team object"
        required: true
        schema:
          $ref: "#/definitions/Organization"
      responses:
        201:
          description: "successful operation"
          headers:
            Location:
              type: "string"
      x-swagger-router-controller: "Org"
  /org/{name}:
    get:
      tags:
      - "org"
      summary: "Get org"
      description: "Get a org"
      operationId: "getOrg"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "The id of the team"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Organization"
        404:
          description: "Team not found"
      x-swagger-router-controller: "Org"
    put:
      tags:
      - "org"
      summary: "Modify org (generally adding or removing users)"
      description: "Modify an existing team"
      operationId: "updateOrg"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "The id of the team that needs to be fetched"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Modified team object"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "Org"
definitions:
  Organization:
    type: "object"
    properties:
      name:
        type: "string"
      members:
        type: "array"
        items:
          $ref: "#/definitions/Runner"
  Runner:
    type: "object"
    properties:
      username:
        type: "string"
      gender:
        type: "integer"
      meters:
        type: "integer"
